Novos itens para o glossário
mentoriaiac/glossario pull request #16
Opened 2021-11-08 21:43 UTC by fcpimenta

# Titulo: Incluir novos itens no glossário

Após ler alguns repositórios da mentoria, encontrei itens e produtos que achei relevante incluir no glossário.

- [X] Garanta que seu **topic/feature/bugfix branch** tenha uma branch nomeada e não a sua branch main esteja no PR
- [X] Dê um titulo que expresse o objetivo do PR
- [ ] Associe seu PR a uma Issue criada no repositósito. Caso seja uma correção de linguagem ou pequenas correções, não é necessário
- [X] Descreva o objetivo do PR
- [ ] Inclua links relevantes para a sua modificação/sugestão/correção
- [ ] Descreva um passo-a-passo para testar o seu PR

## Issue

## Objetivo

## Referências

## Como testar

2021-11-14 13:38 UTC, gomex requested changes
As contribuições estão muito boas, mas tem poucos pontos que merecem atenção.

2021-11-14 13:38 UTC, gomex commented on README.md
> +### [CI/CD](https://www.digitalocean.com/community/tutorials/digitalocean-community-glossary)
Eu acho que podemos separar o CI do CD e depois apresentar juntos, o que acha?

2021-11-14 13:38 UTC, gomex commented on README.md
> +Consul é uma solução de service mesh (malha de serviço) que fornece um plano de controle completo com descoberta de serviço, configuração e funcionalidade de segmentação. Cada um desses recursos pode
Não entendi essa parte "O Consul requer um plano de dados"

2021-11-14 13:38 UTC, gomex commented on README.md
> +Pipeline de entrega contínua (CD) é o conjunto de etapas pelo qual as mudanças de código vão passar para chegar até a produção.
Pode ter pipeline só de CI também. Acho que podemos refazer esse texto pra deixar mais abrangente.

2021-11-14 13:38 UTC, gomex commented on README.md
> +### [Pull Request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests)
Os links, sempre que possível, seria legal colocar em pt-br. Se não achar outro, eu tenho um artigo sobre isso: https://gomex.me/2020/07/05/precisamos-falar-sobre-pull-request/

2021-11-16 13:47 UTC, fcpimenta commented on README.md
> +### [CI/CD](https://www.digitalocean.com/community/tutorials/digitalocean-community-glossary)
Sim, concordo. Achei interessantes as definições da Red Hat.

2021-11-16 13:47 UTC, fcpimenta commented on README.md
> +Consul é uma solução de service mesh (malha de serviço) que fornece um plano de controle completo com descoberta de serviço, configuração e funcionalidade de segmentação. Cada um desses recursos pode
Mantive a expressão em Inglês (data plane) e adicionei uma breve explicação.

2021-11-16 13:48 UTC, fcpimenta commented on README.md
> +Pipeline de entrega contínua (CD) é o conjunto de etapas pelo qual as mudanças de código vão passar para chegar até a produção.
Si, eu acabei fixando apenas na entrega. Refiz as definições usando a abordagem da Red Hat, que achei bem didática.

2021-11-16 13:49 UTC, fcpimenta commented on README.md
> +### [Pull Request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests)
Vou sempre buscar links em pt-br. Bem observado.

2021-11-21 13:50 UTC, gomex approved these changes
Muito bom! Obrigado!

2021-11-21 13:50 UTC, merged