update Readme
mentoriaiac/glossario pull request #9
Opened 2021-08-23 07:32 UTC by julialamenza

# Adicionando RKE ao glossário

Adicionei RKE ao glossario 

- [ x] Garanta que seu **topic/feature/bugfix branch** tenha uma branch nomeada e não a sua branch main esteja no PR
- [ x] Dê um titulo que expresse o objetivo do PR
- [ ] Associe seu PR a uma Issue criada no repositósito. Caso seja uma correção de linguagem ou pequenas correções, não é necessário
- [x ] Descreva o objetivo do PR
- [ ] Inclua links relevantes para a sua modificação/sugestão/correção
- [ ] Descreva um passo-a-passo para testar o seu PR

## Issue

## Objetivo

## Referências

## Como testar

2021-08-23 14:16 UTC, afonsoaugusto requested changes

2021-08-23 14:16 UTC, afonsoaugusto commented on README.md
> +RKE é o engine de criação de cluster k8s da [rancher](https://rancher.com/)
Opa, acho que poderia colocar um pouco mais detalhe, para ficar mais explicito o que o rke faz.
No caso, falar que ele é um binário que faz a instalação e a configuração do K8S.
Que ele seria algo semelhante ao [KOPS](https://kops.sigs.k8s.io/)

2021-08-23 14:36 UTC, julialamenza commented on README.md
> +RKE é o engine de criação de cluster k8s da [rancher](https://rancher.com/)
done

2021-08-29 17:03 UTC, afonsoaugusto approved these changes

2021-08-29 17:04 UTC, afonsoaugusto commented
Show demias @julialamenza, acho que seria legal mergeamos o pr.

psc, @mentoriaiac/moderadores

2021-08-29 18:18 UTC, merged